# Generated by Django 5.1.5 on 2025-09-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='current_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
