# Generated by Django 5.1.5 on 2025-09-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_current_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.JSONField()),
                ('end_location', models.JSONField()),
                ('distance', models.FloatField()),
                ('duration', models.FloatField()),
                ('driving_hours', models.FloatField()),
                ('rests', models.JSONField(default=list)),
                ('fuel_stops', models.IntegerField()),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('steps', models.JSONField(default=list)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='trips.trip')),
            ],
        ),
    ]
